export default {
    dog_light: require('../../assets/icons/dog_light.svg'),
    // dog_dark: require('../../assets/icons/dog_light.svg'),
    // home_light: require('../../assets/icons/home.svg'),
    // home_dark: require('../../assets/icons/dog_dark.png'),
    map_light: require('../../assets/icons/map_light.svg'),
    // map_dark: require('../../assets/icons/dog_dark.png'),
    message_light: require('../../assets/icons/message_light.svg'),
    // message_dark: require('../../assets/icons/dog_dark.png'),
    plus: require('../../assets/icons/plus.svg'),
    like: require('../../assets/icons/like.svg'),
    small_search: require('../../assets/icons/small_search.svg'),
    voice: require('../../assets/icons/voice.svg'),
    restaurants: require('../../assets/icons/restaurants.svg'),
    cafes: require('../../assets/icons/cafes.svg'),
    dog_walks: require('../../assets/icons/dog_walks.svg'),
    dog_parks: require('../../assets/icons/dog_parks.svg'),
    groomers: require('../../assets/icons/groomers.svg'),
    vets: require('../../assets/icons/vets.svg'),
    photo_spots: require('../../assets/icons/photo_spots.svg'),
    more: require('../../assets/icons/more.svg'),
}